# Generated by Django 3.2.3 on 2021-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='Вопрос')),
                ('category', models.CharField(choices=[('Занятия', 'Занятия'), ('Работа Вуза', 'Работа Вуза'), ('Преподаватели', 'Преподаватели'), ('Другой вопрос', 'Другой вопрос')], default='Другой вопрос', max_length=64, verbose_name='Категория')),
                ('answer', models.TextField(default=None, null=True, verbose_name='Ответ')),
                ('count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
